included:
  - Sources
  - Tests

statement_position:
  statement_mode: uncuddled_else

disabled_rules:
  - cyclomatic_complexity
  - empty_parentheses_with_trailing_closure
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - line_length
  - operator_whitespace
  - redundant_string_enum_value
  - todo
  - trailing_whitespace
  - type_body_length
  - unused_closure_parameter
  - variable_name
  