included:
  - Sources
  - Tests

statement_position:
  statement_mode: uncuddled_else

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - explicit_init
  - explicit_top_level_acl
  - first_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - no_extension_access_modifier
  - operator_usage_whitespace
  - override_in_extension
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
   
disabled_rules:
  - cyclomatic_complexity
  - empty_parentheses_with_trailing_closure
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - notification_center_detachment
  - operator_whitespace
  - private_over_fileprivate
  - redundant_string_enum_value
  - switch_case_alignment
  - todo
  - trailing_whitespace
  - type_body_length
  - unused_closure_parameter
  - unused_optional_binding
  
