included:
  - Sources
  - Tests

statement_position:
  statement_mode: uncuddled_else

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - explicit_init
  - explicit_top_level_acl
  - no_extension_access_modifier
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  
disabled_rules:
  - cyclomatic_complexity
  - empty_parentheses_with_trailing_closure
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - notification_center_detachment
  - operator_whitespace
  - redundant_string_enum_value
  - todo
  - trailing_whitespace
  - type_body_length
  - unused_closure_parameter
  